version: '3.7'

services:

  api:
    image: eassbhhtgu/api:latest
    depends_on:
    - weatherforecast
    entrypoint: bash -c '/usr/sbin/update-ca-certificates && dotnet Api.WebApplication.dll'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: '443'
      ASPNETCORE_URLS: https://+
      Endpoints:WeatherForecast: https://weatherforecast
      Kestrel:Certificates:Default:KeyPath: /usr/localhost.key
      Kestrel:Certificates:Default:Path: /usr/localhost.crt
    ports:
    - 50927:443/tcp
    volumes:
    - ~/.aspnet/https/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro
    - ~/.aspnet/https/api.crt:/usr/localhost.crt:ro
    - ~/.aspnet/https/api.key:/usr/localhost.key:ro

  weatherforecast:
    image: eassbhhtgu/weatherforecast:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: '443'
      ASPNETCORE_URLS: https://+
      Kestrel:Certificates:Default:KeyPath: /usr/localhost.key
      Kestrel:Certificates:Default:Path: /usr/localhost.crt
    volumes:
    - ~/.aspnet/https/weatherforecast.crt:/usr/localhost.crt:ro
    - ~/.aspnet/https/weatherforecast.key:/usr/localhost.key:ro
